"""Add status to RawArticle and create ArticleSection table

Revision ID: 67d06a0a4269
Revises: 976204b9a517
Create Date: 2025-09-20 10:05:53.755191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d06a0a4269'
down_revision: Union[str, None] = '976204b9a517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_article_id', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(), nullable=False),
    sa.Column('section_content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_sections_id'), 'article_sections', ['id'], unique=False)
    op.create_index(op.f('ix_article_sections_raw_article_id'), 'article_sections', ['raw_article_id'], unique=False)
    op.add_column('raw_articles', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_articles', 'status')
    op.drop_index(op.f('ix_article_sections_raw_article_id'), table_name='article_sections')
    op.drop_index(op.f('ix_article_sections_id'), table_name='article_sections')
    op.drop_table('article_sections')
    # ### end Alembic commands ###
