"""Add bilingual support to Article and ArticleSection models

Revision ID: 7138520ab18f
Revises: 9963015b89b6
Create Date: 2025-09-21 10:53:36.872048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7138520ab18f'
down_revision: Union[str, None] = '9963015b89b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_title_en', sa.String(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('section_content_en', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('section_title_te', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('section_content_te', sa.Text(), nullable=True))
        batch_op.drop_column('section_content')
        batch_op.drop_column('section_title')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(), nullable=False, server_default='Untitled'))
        batch_op.add_column(sa.Column('content_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('title_te', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('content_te', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary_te', sa.Text(), nullable=True))
        batch_op.drop_index('ix_articles_title')
        batch_op.create_index(batch_op.f('ix_articles_title_en'), ['title_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_title_te'), ['title_te'], unique=False)
        batch_op.drop_column('summary')
        batch_op.drop_column('title')
        batch_op.drop_column('content')

    with op.batch_alter_table('raw_articles', schema=None) as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(),
                   nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_articles', schema=None) as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(),
                   nullable=True)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('summary', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_articles_title_te'))
        batch_op.drop_index(batch_op.f('ix_articles_title_en'))
        batch_op.create_index('ix_articles_title', ['title'], unique=False)
        batch_op.drop_column('summary_te')
        batch_op.drop_column('content_te')
        batch_op.drop_column('title_te')
        batch_op.drop_column('summary_en')
        batch_op.drop_column('content_en')
        batch_op.drop_column('title_en')

    with op.batch_alter_table('article_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_title', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('section_content', sa.TEXT(), nullable=False))
        batch_op.drop_column('section_content_te')
        batch_op.drop_column('section_title_te')
        batch_op.drop_column('section_content_en')
        batch_op.drop_column('section_title_en')

    # ### end Alembic commands ###
