"""Add image_url to Article and RawArticle models

Revision ID: 976204b9a517
Revises: dd098d97b713
Create Date: 2025-09-06 18:01:10.232669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976204b9a517'
down_revision: Union[str, None] = 'dd098d97b713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_articles', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_articles', 'image_url')
    # ### end Alembic commands ###
