"""Add content_type to Article and RawArticle

Revision ID: 9963015b89b6
Revises: 67d06a0a4269
Create Date: 2025-09-20 10:39:55.527417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9963015b89b6'
down_revision: Union[str, None] = '67d06a0a4269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content_type', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('raw_articles', sa.Column('content_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('raw_articles', 'content_type')
    op.drop_column('articles', 'image_url')
    op.drop_column('articles', 'content_type')
    # ### end Alembic commands ###
