"""Add raw_articles table

Revision ID: dd098d97b713
Revises: 780a41854c5a
Create Date: 2025-08-22 17:32:34.568475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd098d97b713'
down_revision: Union[str, None] = '780a41854c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'raw_articles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('source_url', sa.String(), nullable=False),
        sa.Column('source_name', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('published_date', sa.DateTime(), nullable=True),
        sa.Column('scraped_date', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_articles_category'), 'raw_articles', ['category'], unique=False)
    op.create_index(op.f('ix_raw_articles_id'), 'raw_articles', ['id'], unique=False)
    op.create_index(op.f('ix_raw_articles_source_url'), 'raw_articles', ['source_url'], unique=True)
    op.create_index(op.f('ix_raw_articles_title'), 'raw_articles', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_articles_title'), table_name='raw_articles')
    op.drop_index(op.f('ix_raw_articles_source_url'), table_name='raw_articles')
    op.drop_index(op.f('ix_raw_articles_id'), table_name='raw_articles')
    op.drop_index(op.f('ix_raw_articles_category'), table_name='raw_articles')
    op.drop_table('raw_articles')
    # ### end Alembic commands ###
